
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=personalSql
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - 5454:3306
#    expose:
#      - 3306
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn run start:dev
    restart: unless-stopped
    environment:
#      - DATABASE_PORT=3306
#      - DATABASE_HOST=db
# OVERWRITE ENV
      - DATABASE_HOST=127.0.0.1:5454
      - DATABASE_HOST=host.docker.internal
    ports:
      - 8080:3434

