version: "3"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=personalSql
#      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - "5454:3306"
    expose:
      - 3306
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    depends_on:
      - db
    environment:
            - DATABASE_PORT=3306
            - DATABASE_HOST=db
      # OVERWRITE ENV
#      - DATABASE_HOST=127.0.0.1:5454
#      - DATABASE_HOST=host.docker.internal
    ports:
      - "8080:3434"
