PATCH http://localhost:8080/v1/user/2
Content-Type: application/json

{
  "name": "Tran Huu Loc",
  "email": "tranhuuloc2010@gmail.com",
  "password": "admin@1234",
  "role": "admin"
}

###
DELETE http://localhost:8080/v1/user/1
Content-Type: application/json

###
GET http://localhost:8080/v1/user/1
Accept: application/json

###
GET http://localhost:8080/v1/user
Accept: application/json

###
POST http://localhost:8080/v1/user
Content-Type: application/json

{
  "name": "Tran Huu Loc",
  "email": "tranhuuloc2010@gmail.com",
  "password": "admin@123",
  "role": "admin"
}
